# Generated by Django 3.0.5 on 2020-04-25 10:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64, verbose_name='Название')),
                ('description', models.CharField(blank=True, max_length=160, null=True, verbose_name='Description about team')),
                ('image', models.ImageField(upload_to='lot_images/', verbose_name='Изображение лота')),
                ('limit_players', models.PositiveSmallIntegerField(blank=True, default=1, verbose_name='Максимальное кол-во участников')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Дата изменений')),
                ('is_active', models.BooleanField(blank=True, default=True, verbose_name='Active is Team')),
            ],
        ),
        migrations.CreateModel(
            name='LotNumber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num', models.PositiveSmallIntegerField(blank=True, default=1, verbose_name='Номер')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Дата изменений')),
                ('lot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Лотерея', to='lots.Lot')),
            ],
        ),
    ]
