# Generated by Django 3.0.5 on 2020-09-11 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Condition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Youtube', max_length=32)),
                ('link', models.URLField()),
                ('icon', models.CharField(default='cloud', max_length=32)),
                ('color', models.CharField(default='#ffffff', max_length=16)),
                ('subscribe', models.BooleanField(default=False)),
                ('like', models.BooleanField(default=False)),
                ('repost', models.BooleanField(default=False)),
                ('comment', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Lot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=48, verbose_name='Название')),
                ('description', models.CharField(blank=True, max_length=160, null=True, verbose_name='Описание')),
                ('image', models.ImageField(blank=True, null=True, upload_to='lot_images/', verbose_name='Основное изображение')),
                ('image_two', models.ImageField(blank=True, null=True, upload_to='lot_images/', verbose_name='Дополнительное фото')),
                ('image_three', models.ImageField(blank=True, null=True, upload_to='lot_images/', verbose_name='Дополнительное фото')),
                ('image_four', models.ImageField(blank=True, null=True, upload_to='lot_images/', verbose_name='Дополнительное фото')),
                ('players', models.PositiveSmallIntegerField(default=3, verbose_name='Максимальное кол-во участников')),
                ('winners', models.PositiveSmallIntegerField(blank=True, default=1, verbose_name='Кол-во победилей')),
                ('winners_complete', models.CharField(max_length=32, null=True, verbose_name='Winners complete')),
                ('energy', models.PositiveSmallIntegerField(default=1, verbose_name='Первоначальная затрата энергии на один ход')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Дата изменений')),
                ('start', models.DateTimeField(null=True, verbose_name='Дата старта')),
                ('free', models.BooleanField(blank=True, default=True, verbose_name='Свободные места')),
                ('active', models.BooleanField(blank=True, default=True, verbose_name='Активность игры')),
            ],
        ),
    ]
