# Generated by Django 3.0.5 on 2020-04-28 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lots', '0002_auto_20200425_1752'),
    ]

    operations = [
        migrations.AddField(
            model_name='lot',
            name='energy',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='Первоночальная затрата энергии на один ход'),
        ),
        migrations.AddField(
            model_name='lot',
            name='winners',
            field=models.PositiveSmallIntegerField(blank=True, default=1, verbose_name='Кол-во победилей'),
        ),
        migrations.AlterField(
            model_name='lot',
            name='description',
            field=models.CharField(blank=True, max_length=160, null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='lot',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='lot_images/', verbose_name='Изображение лота'),
        ),
        migrations.AlterField(
            model_name='lot',
            name='limit_players',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='Максимальное кол-во участников'),
        ),
        migrations.AlterField(
            model_name='lot',
            name='title',
            field=models.CharField(max_length=48, verbose_name='Название'),
        ),
    ]
