# Generated by Django 3.0.5 on 2020-09-12 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lots', '0002_auto_20200911_1002'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lot',
            name='free',
        ),
        migrations.RemoveField(
            model_name='lot',
            name='image_four',
        ),
        migrations.RemoveField(
            model_name='lot',
            name='image_three',
        ),
        migrations.RemoveField(
            model_name='lot',
            name='image_two',
        ),
        migrations.RemoveField(
            model_name='lot',
            name='start',
        ),
        migrations.RemoveField(
            model_name='lot',
            name='winners_complete',
        ),
        migrations.AlterField(
            model_name='lot',
            name='energy',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='Затрата энергии'),
        ),
        migrations.AlterField(
            model_name='lot',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='lot/', verbose_name='Основное изображение'),
        ),
        migrations.AlterField(
            model_name='lot',
            name='players',
            field=models.PositiveSmallIntegerField(default=3, verbose_name='Кол-во участников'),
        ),
    ]
