# Generated by Django 3.0.5 on 2020-09-12 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lots', '0003_auto_20200912_1129'),
    ]

    operations = [
        migrations.AddField(
            model_name='lot',
            name='winners_complete',
            field=models.DateTimeField(null=True),
        ),
    ]
