# Generated by Django 3.0.5 on 2020-09-14 03:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lots', '0004_lot_winners_complete'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lot',
            old_name='creator',
            new_name='user',
        ),
    ]
