# Generated by Django 3.0.5 on 2020-04-29 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lots', '0004_auto_20200428_1445'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lot',
            name='energy',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='Первоначальная затрата энергии на один ход'),
        ),
    ]
