# Generated by Django 3.0.5 on 2020-05-01 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lots', '0006_auto_20200501_1817'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lot',
            old_name='is_active',
            new_name='active',
        ),
        migrations.RenameField(
            model_name='lot',
            old_name='is_free',
            new_name='free',
        ),
    ]
