# Generated by Django 3.0.5 on 2020-05-01 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lots', '0007_auto_20200501_1851'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lot',
            name='active',
            field=models.BooleanField(blank=True, default=True, verbose_name='Активность игры'),
        ),
    ]
