# Generated by Django 3.0.5 on 2020-05-09 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lots', '0009_lot_code'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lot',
            old_name='limit_players',
            new_name='players',
        ),
    ]
