# Generated by Django 3.0.5 on 2020-05-09 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lots', '0010_auto_20200509_2124'),
    ]

    operations = [
        migrations.AddField(
            model_name='lot',
            name='start',
            field=models.DateTimeField(null=True, verbose_name='Дата старта'),
        ),
    ]
