# Generated by Django 3.0.5 on 2020-05-15 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lots', '0011_lot_start'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lot',
            name='code',
        ),
        migrations.AddField(
            model_name='lot',
            name='condition',
            field=models.PositiveSmallIntegerField(blank=True, default=0, verbose_name='Условие'),
        ),
    ]
