# Generated by Django 3.0.5 on 2020-05-18 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lots', '0014_auto_20200518_1405'),
    ]

    operations = [
        migrations.RenameField(
            model_name='condition',
            old_name='type',
            new_name='title',
        ),
        migrations.AddField(
            model_name='condition',
            name='color',
            field=models.CharField(default='Youtube', max_length=16),
        ),
        migrations.AddField(
            model_name='condition',
            name='icon',
            field=models.CharField(default='mdi-cloud-question', max_length=32),
        ),
        migrations.AddField(
            model_name='condition',
            name='value',
            field=models.CharField(default='11', max_length=8),
            preserve_default=False,
        ),
    ]
