# Generated by Django 3.0.5 on 2020-05-19 06:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lots', '0015_auto_20200518_1504'),
    ]

    operations = [
        migrations.AlterField(
            model_name='condition',
            name='lot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='condition_set', to='lots.Lot'),
        ),
    ]
