# Generated by Django 3.0.5 on 2020-05-19 08:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lots', '0018_auto_20200519_1544'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='condition',
            name='actions',
        ),
    ]
