# Generated by Django 3.0.5 on 2020-06-10 03:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('lots', '0020_auto_20200519_1613'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lot',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='lotnumber',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Date create'),
        ),
        migrations.AlterField(
            model_name='lotnumber',
            name='lot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Lot', to='lots.Lot'),
        ),
        migrations.AlterField(
            model_name='lotnumber',
            name='num',
            field=models.PositiveSmallIntegerField(blank=True, default=1, verbose_name='Number'),
        ),
        migrations.AlterField(
            model_name='lotnumber',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Owner', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='lotnumber',
            name='updated',
            field=models.DateTimeField(auto_now=True, verbose_name='Date update'),
        ),
    ]
