# Generated by Django 3.0.5 on 2020-06-20 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lots', '0022_lotnumber_won'),
    ]

    operations = [
        migrations.AddField(
            model_name='lot',
            name='winners_complete',
            field=models.CharField(max_length=32, null=True, verbose_name='Winners complete'),
        ),
    ]
