# Generated by Django 3.0.5 on 2020-07-27 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lots', '0024_auto_20200727_0104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lotimage',
            name='image',
            field=models.ImageField(default='lot_images/d_JXENrkQ.jfif', upload_to='lot_images/', verbose_name='Изображение лота'),
            preserve_default=False,
        ),
    ]
