# Generated by Django 3.0.5 on 2020-07-27 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lots', '0025_auto_20200727_1126'),
    ]

    operations = [
        migrations.AddField(
            model_name='lot',
            name='image_four',
            field=models.ImageField(blank=True, null=True, upload_to='lot_images/', verbose_name='Дополнительное фото'),
        ),
        migrations.AddField(
            model_name='lot',
            name='image_three',
            field=models.ImageField(blank=True, null=True, upload_to='lot_images/', verbose_name='Дополнительное фото'),
        ),
        migrations.AddField(
            model_name='lot',
            name='image_two',
            field=models.ImageField(blank=True, null=True, upload_to='lot_images/', verbose_name='Дополнительное фото'),
        ),
    ]
