# Generated by Django 3.0.5 on 2020-07-28 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lots', '0026_auto_20200727_1237'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='condition',
            name='value',
        ),
        migrations.AlterField(
            model_name='condition',
            name='color',
            field=models.CharField(default='#ffffff', max_length=16),
        ),
        migrations.AlterField(
            model_name='condition',
            name='icon',
            field=models.CharField(default='cloud', max_length=32),
        ),
    ]
