# Generated by Django 3.0.5 on 2020-08-02 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lots', '0027_auto_20200728_2201'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LotImage',
        ),
    ]
