# Generated by Django 3.0.5 on 2020-09-06 09:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lots', '0028_delete_lotimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Actions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(default='Подписка', max_length=16)),
                ('condition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='action_set', to='lots.Condition')),
            ],
        ),
    ]
