# Generated by Django 3.0.5 on 2020-09-06 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lots', '0029_actions'),
    ]

    operations = [
        migrations.AddField(
            model_name='condition',
            name='comment',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='condition',
            name='like',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='condition',
            name='repost',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='condition',
            name='subscribe',
            field=models.BooleanField(default=False),
        ),
    ]
