# Generated by Django 3.0.5 on 2020-09-06 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lots', '0030_auto_20200906_2259'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Action',
        ),
        migrations.DeleteModel(
            name='Actions',
        ),
    ]
