# Generated by Django 3.0.5 on 2020-06-06 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TaskTime',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32, verbose_name='Название')),
                ('description', models.CharField(blank=True, max_length=80, null=True, verbose_name='Описание')),
                ('in_on_time', models.BooleanField(default=False, verbose_name='Подряд или любое')),
                ('active', models.BooleanField(blank=True, default=True, verbose_name='Активность задания')),
                ('time', models.PositiveSmallIntegerField(default=1, verbose_name='Необходимое время в минутах')),
                ('energy', models.PositiveSmallIntegerField(default=1, verbose_name='Необходимое время')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
            ],
        ),
    ]
