# Generated by Django 3.0.5 on 2020-06-06 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasktime',
            name='max_level',
            field=models.PositiveSmallIntegerField(null=True, verbose_name='Максимальный уровень использования'),
        ),
    ]
