# Generated by Django 3.0.5 on 2020-06-07 10:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('my_user', '0015_delete_tasks'),
        ('task', '0002_tasktime_max_level'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tasks',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('now_time', models.PositiveSmallIntegerField(blank=True, default=0, verbose_name='Времени в онлайне')),
                ('day_time', models.PositiveSmallIntegerField(blank=True, default=0, verbose_name='Времени за день')),
                ('word', models.CharField(max_length=32, null=True, verbose_name='Секретное слово')),
            ],
        ),
        migrations.DeleteModel(
            name='TaskTime',
        ),
    ]
