# Generated by Django 3.0.5 on 2020-06-07 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0003_auto_20200607_1717'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasks',
            name='day_success',
            field=models.BooleanField(default=False, verbose_name='Времени за день выполнено'),
        ),
        migrations.AddField(
            model_name='tasks',
            name='level_success',
            field=models.BooleanField(default=False, verbose_name='Времени за уровень выполнено'),
        ),
        migrations.AddField(
            model_name='tasks',
            name='level_time',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Время за уровень'),
        ),
        migrations.AddField(
            model_name='tasks',
            name='now_success',
            field=models.BooleanField(default=False, verbose_name='Времени в онлайне выполнено'),
        ),
        migrations.AlterField(
            model_name='tasks',
            name='day_time',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Времени за день'),
        ),
        migrations.AlterField(
            model_name='tasks',
            name='now_time',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Времени в онлайне'),
        ),
    ]
