# Generated by Django 3.0.5 on 2020-05-01 15:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('my_user', '0002_user_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('name', models.CharField(max_length=48, verbose_name='Название компании')),
                ('phrase', models.CharField(max_length=96, verbose_name='Лозунг компании')),
                ('count_games', models.PositiveSmallIntegerField(verbose_name='Количество игр')),
                ('count_rating', models.PositiveSmallIntegerField(verbose_name='Количество отзывов')),
                ('rating', models.FloatField(verbose_name='Рейтинг отзывов')),
                ('image', models.ImageField(blank=True, null=True, upload_to='companies_logo/', verbose_name='Лого компании')),
                ('create', models.DateField(auto_now_add=True, verbose_name='Дата создания')),
            ],
        ),
    ]
