# Generated by Django 3.0.5 on 2020-05-11 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='color',
            field=models.CharField(max_length=24, null=True, verbose_name='Цвет компании'),
        ),
    ]
