# Generated by Django 3.0.5 on 2020-05-21 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0003_company_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='color_text',
            field=models.CharField(max_length=24, null=True, verbose_name='Цвет текста компании'),
        ),
    ]
