# Generated by Django 3.0.5 on 2020-05-22 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0004_company_color_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='color_type',
            field=models.CharField(max_length=24, null=True, verbose_name='Оттенок цвета'),
        ),
        migrations.AlterField(
            model_name='company',
            name='count_games',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Количество игр'),
        ),
        migrations.AlterField(
            model_name='company',
            name='count_rating',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Количество отзывов'),
        ),
        migrations.AlterField(
            model_name='company',
            name='rating',
            field=models.FloatField(default=0, verbose_name='Рейтинг отзывов'),
        ),
    ]
