# Generated by Django 3.0.5 on 2020-06-06 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0005_auto_20200522_1058'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='believe',
            field=models.PositiveSmallIntegerField(blank=True, default=0, verbose_name='Индекс доверия в процентов'),
        ),
        migrations.AlterField(
            model_name='company',
            name='phrase',
            field=models.CharField(max_length=96, null=True, verbose_name='Лозунг компании'),
        ),
    ]
