# Generated by Django 3.0.5 on 2020-09-12 04:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_user', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='diamonds',
        ),
        migrations.RemoveField(
            model_name='user',
            name='level',
        ),
        migrations.RemoveField(
            model_name='user',
            name='notification',
        ),
        migrations.RemoveField(
            model_name='user',
            name='sound',
        ),
        migrations.RemoveField(
            model_name='user',
            name='stars',
        ),
        migrations.RemoveField(
            model_name='user',
            name='theme',
        ),
    ]
