# Generated by Django 3.0.5 on 2020-09-12 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_user', '0002_auto_20200912_1112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='user/', verbose_name='Аватар'),
        ),
    ]
