# Generated by Django 3.0.5 on 2020-05-11 05:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('my_user', '0003_user_aura'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('list', models.CharField(max_length=24, null=True)),
                ('country', models.CharField(max_length=64, null=True)),
                ('city', models.CharField(max_length=64, null=True)),
                ('district', models.CharField(max_length=64, null=True)),
                ('street', models.CharField(max_length=64, null=True)),
                ('house', models.CharField(max_length=16, null=True)),
                ('phone_number', models.CharField(max_length=32, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='language',
            field=models.CharField(default='ru', max_length=16, verbose_name='Язык системы'),
        ),
        migrations.AlterField(
            model_name='user',
            name='balls',
            field=models.IntegerField(blank=True, default=0, verbose_name='Баллы пользователя'),
        ),
        migrations.AlterField(
            model_name='user',
            name='locale',
            field=models.CharField(default='ru', max_length=16, verbose_name='Локация пользователя'),
        ),
    ]
