# Generated by Django 3.0.5 on 2020-05-11 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_user', '0004_auto_20200511_1226'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='aura',
        ),
        migrations.AddField(
            model_name='user',
            name='karma',
            field=models.SmallIntegerField(blank=True, default=0, verbose_name='Карма пользователя'),
        ),
    ]
