# Generated by Django 3.0.5 on 2020-05-11 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_user', '0005_auto_20200511_1400'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='balls',
            new_name='stars',
        ),
    ]
