# Generated by Django 3.0.5 on 2020-05-12 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_user', '0006_auto_20200511_2101'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='theme',
            field=models.PositiveSmallIntegerField(blank=True, default=0, verbose_name='Тема дисплея'),
        ),
    ]
