# Generated by Django 3.0.5 on 2020-06-06 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_user', '0007_user_theme'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='list',
        ),
        migrations.AddField(
            model_name='address',
            name='index',
            field=models.CharField(max_length=24, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='level',
            field=models.PositiveSmallIntegerField(blank=True, default=0, verbose_name='Уровень'),
        ),
    ]
