# Generated by Django 3.0.5 on 2020-06-06 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_user', '0008_auto_20200606_1153'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='notification',
            field=models.BooleanField(default=True, verbose_name='Уведомления'),
        ),
        migrations.AddField(
            model_name='user',
            name='sound',
            field=models.BooleanField(default=True, verbose_name='Звук'),
        ),
    ]
