# Generated by Django 3.0.5 on 2020-06-06 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_user', '0009_auto_20200606_1550'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='time_full',
            field=models.PositiveSmallIntegerField(blank=True, default=0, verbose_name='Времени за день'),
        ),
        migrations.AddField(
            model_name='user',
            name='time_online',
            field=models.PositiveSmallIntegerField(blank=True, default=0, verbose_name='Времени в онлайне'),
        ),
        migrations.AddField(
            model_name='user',
            name='word',
            field=models.CharField(max_length=32, null=True, verbose_name='Секретное слово'),
        ),
    ]
