# Generated by Django 3.0.5 on 2020-06-06 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_user', '0010_auto_20200606_2332'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='level',
            field=models.PositiveSmallIntegerField(blank=True, default=1, verbose_name='Уровень'),
        ),
    ]
