# Generated by Django 3.0.5 on 2020-06-07 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_user', '0011_auto_20200606_2333'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tasks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_online', models.PositiveSmallIntegerField(blank=True, default=0, verbose_name='Времени в онлайне')),
                ('time_full', models.PositiveSmallIntegerField(blank=True, default=0, verbose_name='Времени за день')),
                ('word', models.CharField(max_length=32, null=True, verbose_name='Секретное слово')),
            ],
        ),
        migrations.RemoveField(
            model_name='user',
            name='time_full',
        ),
        migrations.RemoveField(
            model_name='user',
            name='time_online',
        ),
        migrations.RemoveField(
            model_name='user',
            name='word',
        ),
    ]
