# Generated by Django 3.0.5 on 2020-06-07 09:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('my_user', '0012_auto_20200607_1609'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tasks',
            old_name='time_online',
            new_name='time_now',
        ),
        migrations.RemoveField(
            model_name='tasks',
            name='id',
        ),
        migrations.AddField(
            model_name='tasks',
            name='user',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
