# Generated by Django 3.0.5 on 2020-06-07 09:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_user', '0013_auto_20200607_1617'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tasks',
            old_name='time_full',
            new_name='day_time',
        ),
        migrations.RenameField(
            model_name='tasks',
            old_name='time_now',
            new_name='now_time',
        ),
    ]
