# Generated by Django 3.0.5 on 2020-06-07 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_user', '0014_auto_20200607_1635'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Tasks',
        ),
    ]
