# Generated by Django 3.0.5 on 2020-06-10 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_user', '0015_delete_tasks'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='diamonds',
            field=models.PositiveIntegerField(blank=True, default=15, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='user',
            name='energy',
            field=models.PositiveSmallIntegerField(default=15, verbose_name='Энергия'),
        ),
        migrations.AlterField(
            model_name='user',
            name='karma',
            field=models.SmallIntegerField(default=0, verbose_name='Карма пользователя'),
        ),
        migrations.AlterField(
            model_name='user',
            name='level',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='Уровень'),
        ),
        migrations.AlterField(
            model_name='user',
            name='locale',
            field=models.CharField(default='ru', max_length=16, verbose_name='Локация сервера'),
        ),
        migrations.AlterField(
            model_name='user',
            name='stars',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Баллы пользователя'),
        ),
        migrations.AlterField(
            model_name='user',
            name='theme',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Тема дисплея'),
        ),
    ]
