# Generated by Django 3.0.5 on 2020-09-12 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tracker',
            name='day_minutes',
        ),
        migrations.RemoveField(
            model_name='tracker',
            name='days_all',
        ),
        migrations.RemoveField(
            model_name='tracker',
            name='level_minutes',
        ),
        migrations.RemoveField(
            model_name='tracker',
            name='now_minutes',
        ),
        migrations.RemoveField(
            model_name='tracker',
            name='now_ready',
        ),
        migrations.RemoveField(
            model_name='tracker',
            name='time',
        ),
    ]
