# Generated by Django 3.0.5 on 2020-06-10 04:08

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Time',
            new_name='Tracker',
        ),
        migrations.RenameField(
            model_name='tracker',
            old_name='tracker',
            new_name='time',
        ),
    ]
