# Generated by Django 3.0.5 on 2020-09-12 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0002_auto_20200912_2241'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tracker',
            old_name='date',
            new_name='created',
        ),
        migrations.AlterField(
            model_name='tracker',
            name='days_row',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='Track days in one row time'),
        ),
    ]
