# Generated by Django 3.0.5 on 2020-06-10 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0002_auto_20200610_1108'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tracker',
            name='time',
        ),
        migrations.AddField(
            model_name='tracker',
            name='day_time',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Track day time'),
        ),
        migrations.AddField(
            model_name='tracker',
            name='level_time',
            field=models.PositiveIntegerField(default=0, verbose_name='Track level time'),
        ),
    ]
