# Generated by Django 3.0.5 on 2020-09-12 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0003_auto_20200912_2252'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tracker',
            old_name='created',
            new_name='date',
        ),
    ]
