# Generated by Django 3.0.5 on 2020-06-12 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0003_auto_20200610_1348'),
    ]

    operations = [
        migrations.AddField(
            model_name='tracker',
            name='days_all',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Track days all'),
        ),
        migrations.AddField(
            model_name='tracker',
            name='days_row',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Track days in one row time'),
        ),
    ]
