# Generated by Django 3.0.5 on 2020-06-12 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0004_auto_20200612_1319'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tracker',
            name='day_time',
        ),
        migrations.RemoveField(
            model_name='tracker',
            name='level_time',
        ),
        migrations.AddField(
            model_name='tracker',
            name='day_minutes',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Track day minutes'),
        ),
        migrations.AddField(
            model_name='tracker',
            name='level_minutes',
            field=models.PositiveIntegerField(default=0, verbose_name='Track level minutes'),
        ),
    ]
