# Generated by Django 3.0.5 on 2020-06-17 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0005_auto_20200612_1452'),
    ]

    operations = [
        migrations.AddField(
            model_name='tracker',
            name='time',
            field=models.TimeField(null=True),
        ),
    ]
