# Generated by Django 3.0.5 on 2020-06-17 02:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0007_auto_20200617_0949'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tracker',
            name='time',
            field=models.TimeField(default=datetime.time(9, 51, 25, 115794)),
        ),
    ]
