# Generated by Django 3.0.5 on 2020-06-17 03:10

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0008_auto_20200617_0951'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tracker',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 17, 3, 10, 10, 678399, tzinfo=utc)),
        ),
    ]
