# Generated by Django 3.0.5 on 2020-06-17 03:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0009_auto_20200617_1010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tracker',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 17, 10, 18, 41, 814165)),
        ),
    ]
