# Generated by Django 3.0.5 on 2020-06-17 05:10

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0010_auto_20200617_1018'),
    ]

    operations = [
        migrations.AddField(
            model_name='tracker',
            name='now_minutes',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Tracking online minutes'),
        ),
        migrations.AddField(
            model_name='tracker',
            name='now_ready',
            field=models.BooleanField(default=False, verbose_name='Ready online track on today'),
        ),
        migrations.AlterField(
            model_name='tracker',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 17, 5, 10, 14, 178243, tzinfo=utc)),
        ),
    ]
