# Generated by Django 3.0.5 on 2020-06-20 03:54

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0011_auto_20200617_1210'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tracker',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 20, 3, 54, 4, 718344, tzinfo=utc)),
        ),
    ]
