# Generated by Django 3.0.5 on 2020-06-20 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0012_auto_20200620_1054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tracker',
            name='time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
